[package]
name = "lz-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lz-schema.workspace = true
lz-core.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
rand.workspace = true
tracing.workspace = true
